### ISSUE TITLE
Consider documenting publicPath in Webpack docs. 

### ISSUE THREAD

**Issue by TheLarkInn** [rafaelrinaldi/til#1]
I love the write up you have made. Would you consider contributing this information on github.com/webpack/webpack.js.org ? 

Thank you

**Comment by rafaelrinaldi** [comment]
Hey @TheLarkInn I'm glad that you find this helpful! Sure thing, will submit a PR as soon as I can.

**Comment by TheLarkInn** [comment]
Thank you very much!!!

**Comment by rafaelrinaldi** [comment]
@TheLarkInn Done 🤘
